<?php

namespace Jims\PeteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GBookRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class GBookRepository extends EntityRepository
{
}
