<?php

namespace Jims\PeteBundle\Entity;

/**
 * UgroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UgroupRepository extends \Doctrine\ORM\EntityRepository
{
}
