services:
#    jims_study.example:
#        class: Jims\StudyBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]


    st_user_doctrine_listener:
        class: Jims\StudyBundle\Doctrine\StUserListener
        arguments: [  @security.password_encoder ]
        tags:
            - { name: doctrine.event_listener , event: prePersist    }

    st_twig_extension:
        class: Jims\StudyBundle\Twig\StExtension
        arguments: []
        tags:
            - { name: twig.extension }

    api_problem_subcriber:
        class: Jims\StudyBundle\EventListener\ApiExceptionSubcriber
        arguments: [%kernel.debug%]
        tags:
          - { name: kernel.event_subscriber }

    pagination_factory:
        class: Jims\StudyBundle\Pagination\PaginationFactory
        arguments: ['@router']

    alice.processor.StUser:
        class: Jims\StudyBundle\DataFixtures\ORM\AppProcessor
        arguments: ['@security.user_password_encoder.generic']
        tags:
          - { name: hautelook_alice.alice.processor }

    hautelook_alice.bare_faker:
        class: Faker\Generator
        factory: [ Faker\Factory, create ]
        lazy: true
        arguments:
            - %hautelook_alice.locale%
        calls:
            - [ seed, [ %hautelook_alice.seed% ] ]

    alice.faker.provider.foo:
        class: Jims\StudyBundle\DataFixtures\Faker\FooFaker
        arguments: [ @hautelook_alice.bare_faker ]
        tags: [ { name: hautelook_alice.faker.provider } ]