services:
#    jims_study.example:
#        class: Jims\StudyBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]


    st_user_doctrine_listener:
        class: Jims\StudyBundle\Doctrine\StUserListener
        arguments: [  @security.password_encoder ]
        tags:
            - { name: doctrine.event_listener , event: prePersist    }

    st_twig_extension:
        class: Jims\StudyBundle\Twig\StExtension
        arguments: []
        tags:
            - { name: twig.extension }